version: 3.1.{build}
skip_tags: true
image: Visual Studio 2017 Preview
configuration: Release
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
before_build:
- ps: >-
    dotnet restore

    Push-Location "src/Noobot.Console/Configuration/"

    copy "config.default.json" "config.json"

    Pop-Location
build:
  publish_nuget: true
  include_nuget_references: true
  verbosity: minimal

before_package:
- ps: >-
    Push-Location "src\Noobot.Console\"

    dotnet publish -c "Release" -r "win-x64" -f "netcoreapp2.0"

    Pop-Location
after_build:
- ps: >-
    Push-Location "src\Noobot.Console\"

    $buildPath = Resolve-Path ".\bin\Release\*\win-x64"
    Remove-Item "$buildPath\*.pdb"
    Remove-Item "$buildPath\publish" -Recurse -Force

    Pop-Location

    7z a noobot.zip "$buildPath\*"

test: off
artifacts:
- path: noobot.zip
deploy:
- provider: GitHub
  auth_token:
    secure: 8t4+xbVlkXA/FY3516ThrMibGxfCT7ZcSwyZw7KNwUlCH08KMPtznY2QphEn1n/z
  artifact: noobot.zip,/.*\.nupkg/
  draft: true
  on:
    branch: master